# Generated by Django 2.2 on 2020-08-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencedata',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='referencedata',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
